language: ruby
sudo: required
before_install:
- sudo apt-get update; sudo apt-get install shellcheck
- shellcheck ./setup.sh
- shellcheck ./bpkg.sh
install:
- sudo ./setup.sh
script:
- bpkg update
- bpkg list
- bpkg show bpkg/github
- sudo bpkg install bpkg/github -g
- bpkg install bpkg/term
